version: '3.8'

services:
  web:
    image: stekotek/quick_borrow:v1
    command: /bin/bash entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=quick_borrow
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=quick_borrow
      - POSTGRES_USER=quick_borrow
      - POSTGRES_PASSWORD=quick_borrow

volumes:
  postgres_data:
