# Generated by Django 4.2.4 on 2023-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookloan',
            old_name='loan_date',
            new_name='loan_datetime',
        ),
        migrations.RenameField(
            model_name='bookloan',
            old_name='return_date',
            new_name='return_datetime',
        ),
    ]
